theme: jekyll-theme-modernist
include: [".well-known", ".well-known/brave-rewards-verification.txt"]
title: Sloboda. A Craft & Build Game.
description: Sloboda is the new citybuilding and crafting game set in Ukraine in XVII century.
