theme: jekyll-theme-hacker
include: [".well-known", ".well-known/brave-rewards-verification.txt"]
title: Інтерактивна гра-книга (Interactive Fiction)
description: Гра дозволяє зануритись в бурхливі події 1620х років, які відбувалися на Дикому Полі. Але ви не тільки читаєте історію, а ще і можете вибирати подальший розвиток подій. В залежності від вашого вибору, історія продовжується в різних напрямах, або ж і просто обривається назавжди…
