theme: jekyll-theme-modernist
include: [".well-known", ".well-known/brave-rewards-verification.txt"]
title: Loca Deserta. A Game Universe.
description: Loca Deserta games set in Ukraine in XVII century.
